### ISSUE TITLE
<lablgtk2> failed to build on macOS 10.13 (High Sierra)

### ISSUE THREAD

**Issue by BenHocking** [mht208/homebrew-formal#17]
This is very similar to https://github.com/Homebrew/legacy-homebrew/issues/33703 except:

1. I'm using macOS High Sierra.

2. I do have `camlp4 4.06+1`

Here is some output from my shell (zsh):

```
▶ brew install camlp4
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

Warning: camlp4 4.06+1 is already installed

▶ brew install lablgtk2             
==> Installing lablgtk2 from mht208/formal
==> Downloading https://forge.ocamlcore.org/frs/download.php/979/lablgtk-2.16.0.tar.gz
Already downloaded: /Users/benjaminhocking/Library/Caches/Homebrew/lablgtk2-2.16.0.tar.gz
Warning: Calling ENV.j1 is deprecated!
Use ENV.deparallelize instead.
/usr/local/Homebrew/Library/Taps/mht208/homebrew-formal/lablgtk2.rb:31:in `install'
Please report this to the mht208/formal tap!

==> ./configure --bindir=/usr/local/Cellar/lablgtk2/2.16.0/bin --libdir=/usr/local/Cellar/lablgtk2/2.16.0/lib --mandir=/usr/local/Cellar/lablgtk2/2.16.0/share/man --with-libdir=/usr/local/Cellar/lablgtk2/2.16.0/lib/ocaml --without-glade -
Last 15 lines from /Users/benjaminhocking/Library/Logs/Homebrew/lablgtk2/01.configure:
checking for ocamlopt... ocamlopt
checking ocamlopt version... ok
checking for ocamlc.opt... ocamlc.opt
checking ocamlc.opt version... ok
checking for ocamlopt.opt... ocamlopt.opt
checking ocamlc.opt version... ok
checking for ocamlrun... ocamlrun
checking for ocamldep... ocamldep
checking for ocamldoc... ocamldoc
checking for ocamllex... ocamllex
checking for ocamlyacc... ocamlyacc
checking for ocamlmktop... ocamlmktop
checking for ocamlmklib... ocamlmklib
checking for camlp4o... no
configure: error: Cannot find camlp4o.
```

I've also tried it with `brew install --env=std lablgtk2`:
```
▶ brew install --env=std lablgtk2   
==> Installing lablgtk2 from mht208/formal
==> Downloading https://forge.ocamlcore.org/frs/download.php/979/lablgtk-2.16.0.tar.gz
Already downloaded: /Users/benjaminhocking/Library/Caches/Homebrew/lablgtk2-2.16.0.tar.gz
Warning: Calling ENV.j1 is deprecated!
Use ENV.deparallelize instead.
/usr/local/Homebrew/Library/Taps/mht208/homebrew-formal/lablgtk2.rb:31:in `install'
Please report this to the mht208/formal tap!

==> ./configure --bindir=/usr/local/Cellar/lablgtk2/2.16.0/bin --libdir=/usr/local/Cellar/lablgtk2/2.16.0/lib --mandir=/usr/local/Cellar/lablgtk2/2.16.0/share/man --with-libdir=/usr/local/Cellar/lablgtk2/2.16.0/lib/ocaml --without-glade -
==> make world
Last 15 lines from /Users/benjaminhocking/Library/Logs/Homebrew/lablgtk2/02.make:
/usr/local/Cellar/glib/2.54.2/include/glib-2.0/glib/giochannel.h:165:1: note: 'g_io_channel_read' has been explicitly marked deprecated here
GLIB_DEPRECATED_FOR(g_io_channel_read_chars)
^
/usr/local/Cellar/glib/2.54.2/include/glib-2.0/glib/gmacros.h:423:32: note: expanded from macro 'GLIB_DEPRECATED_FOR'
#define GLIB_DEPRECATED_FOR(f) G_DEPRECATED_FOR(f) _GLIB_EXTERN
                               ^
/usr/local/Cellar/glib/2.54.2/include/glib-2.0/glib/gmacros.h:396:29: note: expanded from macro 'G_DEPRECATED_FOR'
#define G_DEPRECATED_FOR(f) G_DEPRECATED
                            ^
/usr/local/Cellar/glib/2.54.2/include/glib-2.0/glib/gmacros.h:384:37: note: expanded from macro 'G_DEPRECATED'
#define G_DEPRECATED __attribute__((__deprecated__))
                                    ^
3 warnings and 1 error generated.
make[1]: *** [ml_glib.o] Error 2
make: *** [world] Error 2
```

**Comment by mht208** [comment]
We recommend opam (https://opam.ocaml.org) for installing OCaml related packages such as lablgtk2. The lablgtk2 formula has been removed.
